tactician:
    commandbus:
        default:
            middleware:
                - tactician_domain_events.middleware.release_recorded_events
                - tactician.middleware.validator
                - tactician.middleware.doctrine
                - tactician.middleware.command_handler
tactician_domain_event:
    collect_from_all_managed_entities: true
