version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/nginx/server.conf:/etc/nginx/server.conf:ro
    depends_on:
      - php

  db:
    image: postgres:13-alpine
    ports:
      - 5002:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: anydasa
      POSTGRES_USER: anydasa
      POSTGRES_PASSWORD: anydasa

  php:
    build: ./.docker/php
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db:
    driver: local

