version: "3"

services:
  db-test:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: anydasa
      POSTGRES_USER: anydasa
      POSTGRES_PASSWORD: anydasa
    networks:
      - test

  php-test:
    build: ./.docker/php
    environment:
      env: test
      POSTGRESQL_HOST: db-test
    volumes:
      - ./:/app
    depends_on:
      - db-test
    networks:
      - test

  nginx-test:
    image: nginx:alpine
    volumes:
      - ./:/app
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.test.conf:ro
      - ./.docker/nginx/server.conf:/etc/nginx/server.conf:ro
    depends_on:
      - php-test
    networks:
      - test

networks:
  test:
