Api:
    resource: '../src/Presentation/Http/Rest/Controller/'
    type: annotation
    prefix: /api/v1
    defaults: { _format: 'json' }

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger }
