imports:
  - { resource: 'parameters.yaml' }

parameters:
  locale: 'en'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means

  get_set_method_normalizer:
    class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
    tags: [ serializer.normalizer ]

  App\:
    resource: '../src/*'
    exclude: '../src/**/{Migrations}'

  api_exception_subscriber:
    class: App\Presentation\Http\Rest\EventListener\ApiExceptionSubscriber
    arguments: []
    tags:
      - { name: kernel.event_subscriber }

  App\Presentation\Http\Rest\Exception\HttpExceptionMap:
    arguments:
      $exceptionMap:
        App\Domain\Common\Exception\ConflictEntityException: 409
        App\Domain\Common\Exception\EntityNotFoundException: 404
        InvalidArgumentException: 400

  _instanceof:

    App\Application\CommandHandlerInterface:
      public: true
      tags:
        - { name: tactician.handler, typehints: true }

    App\Application\QueryHandlerInterface:
      public: true
      tags:
        - { name: tactician.handler, typehints: true }

  App\Presentation\Http\Rest\Controller\:
    resource: '../src/Presentation/Http/Rest/Controller/*'
    tags: [ 'controller.service_arguments' ]
